[2025-01-10T17:18:04.313+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-10T17:18:04.326+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-10T17:17:00+00:00 [queued]>
[2025-01-10T17:18:04.333+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-10T17:17:00+00:00 [queued]>
[2025-01-10T17:18:04.335+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-10T17:18:04.347+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): append_to_database> on 2025-01-10 17:17:00+00:00
[2025-01-10T17:18:04.352+0000] {standard_task_runner.py:72} INFO - Started process 1342 to run task
[2025-01-10T17:18:04.355+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'append_to_database', 'scheduled__2025-01-10T17:17:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmpcd42ppsu']
[2025-01-10T17:18:04.357+0000] {standard_task_runner.py:105} INFO - Job 149: Subtask append_to_database
[2025-01-10T17:18:04.392+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.append_to_database scheduled__2025-01-10T17:17:00+00:00 [running]> on host 453ac4defedc
[2025-01-10T17:18:04.465+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='append_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T17:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-10T17:17:00+00:00'
[2025-01-10T17:18:04.467+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-10T17:18:04.478+0000] {logging_mixin.py:190} INFO - Lỗi kết nối db: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found (0) (SQLDriverConnect)")
[2025-01-10T17:18:04.479+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-10T17:18:04.486+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-10T17:18:04.487+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_information, task_id=append_to_database, run_id=scheduled__2025-01-10T17:17:00+00:00, execution_date=20250110T171700, start_date=20250110T171804, end_date=20250110T171804
[2025-01-10T17:18:04.530+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-10T17:18:04.546+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-10T17:18:04.550+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
