[2025-01-13T16:19:03.956+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T16:19:03.970+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:18:00+00:00 [queued]>
[2025-01-13T16:19:03.977+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:18:00+00:00 [queued]>
[2025-01-13T16:19:03.977+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-13T16:19:03.988+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): append_to_database> on 2025-01-13 16:18:00+00:00
[2025-01-13T16:19:03.993+0000] {standard_task_runner.py:72} INFO - Started process 2855 to run task
[2025-01-13T16:19:03.996+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'append_to_database', 'scheduled__2025-01-13T16:18:00+00:00', '--job-id', '425', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmpr2z54la6']
[2025-01-13T16:19:03.999+0000] {standard_task_runner.py:105} INFO - Job 425: Subtask append_to_database
[2025-01-13T16:19:04.043+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:18:00+00:00 [running]> on host 453ac4defedc
[2025-01-13T16:19:04.126+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='append_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T16:18:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-13T16:18:00+00:00'
[2025-01-13T16:19:04.128+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T16:19:04.180+0000] {logging_mixin.py:190} INFO - Kết nối thành công!
[2025-01-13T16:19:04.182+0000] {logging_mixin.py:190} INFO - <class 'str'>
[2025-01-13T16:19:04.183+0000] {logging_mixin.py:190} INFO - None
[2025-01-13T16:19:04.185+0000] {logging_mixin.py:190} INFO - Có lỗi khi thực hiện append_database: The second parameter to executemany must be a sequence, iterator, or generator.
[2025-01-13T16:19:04.188+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T16:19:04.196+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T16:19:04.198+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_information, task_id=append_to_database, run_id=scheduled__2025-01-13T16:18:00+00:00, execution_date=20250113T161800, start_date=20250113T161903, end_date=20250113T161904
[2025-01-13T16:19:04.252+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T16:19:04.266+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T16:19:04.271+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
