[2024-12-01T07:04:14.452+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-01T07:04:14.464+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.stream_data_from_api manual__2024-12-01T07:04:13.053325+00:00 [queued]>
[2024-12-01T07:04:14.472+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.stream_data_from_api manual__2024-12-01T07:04:13.053325+00:00 [queued]>
[2024-12-01T07:04:14.475+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-01T07:04:14.487+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-12-01 07:04:13.053325+00:00
[2024-12-01T07:04:14.493+0000] {standard_task_runner.py:72} INFO - Started process 532 to run task
[2024-12-01T07:04:14.495+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'stream_data_from_api', 'manual__2024-12-01T07:04:13.053325+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmpre95hsz1']
[2024-12-01T07:04:14.498+0000] {standard_task_runner.py:105} INFO - Job 8: Subtask stream_data_from_api
[2024-12-01T07:04:14.539+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.stream_data_from_api manual__2024-12-01T07:04:13.053325+00:00 [running]> on host 93ee29924b45
[2024-12-01T07:04:14.603+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T07:04:13.053325+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-01T07:04:13.053325+00:00'
[2024-12-01T07:04:14.606+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-01T07:13:47.694+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2024-12-01T07:13:47.701+0000] {process_utils.py:132} INFO - Sending 15 to group 532. PIDs of all processes in the group: [532]
[2024-12-01T07:13:47.703+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 532
[2024-12-01T07:13:47.705+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-12-01T07:13:47.745+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-01T07:13:47.773+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=532, status='terminated', exitcode=0, started='07:04:14') (532) terminated with exit code 0
[2024-12-01T07:13:47.775+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
[2024-12-01T07:13:47.800+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-01T07:13:49.514+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
