[2024-11-28T16:21:23.502+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T16:21:23.528+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.stream_data_from_api manual__2024-11-28T16:21:21.634239+00:00 [queued]>
[2024-11-28T16:21:23.538+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.stream_data_from_api manual__2024-11-28T16:21:21.634239+00:00 [queued]>
[2024-11-28T16:21:23.539+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-28T16:21:23.557+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-11-28 16:21:21.634239+00:00
[2024-11-28T16:21:23.563+0000] {standard_task_runner.py:72} INFO - Started process 295 to run task
[2024-11-28T16:21:23.567+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'stream_data_from_api', 'manual__2024-11-28T16:21:21.634239+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmp4h1ycea5']
[2024-11-28T16:21:23.572+0000] {standard_task_runner.py:105} INFO - Job 62: Subtask stream_data_from_api
[2024-11-28T16:21:23.624+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.stream_data_from_api manual__2024-11-28T16:21:21.634239+00:00 [running]> on host 3ed14f58f772
[2024-11-28T16:21:23.774+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T16:21:21.634239+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T16:21:21.634239+00:00'
[2024-11-28T16:21:23.782+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T16:22:24.281+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-11-28T16:22:24.283+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-28T16:22:24.293+0000] {process_utils.py:132} INFO - Sending 15 to group 295. PIDs of all processes in the group: [295]
[2024-11-28T16:22:24.294+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 295
[2024-11-28T16:22:24.295+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-28T16:22:24.317+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T16:22:24.348+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=295, status='terminated', exitcode=0, started='16:21:23') (295) terminated with exit code 0
