[2024-11-28T16:22:56.601+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-28T16:22:56.620+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.stream_data_from_api manual__2024-11-28T16:22:55.430403+00:00 [queued]>
[2024-11-28T16:22:56.630+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.stream_data_from_api manual__2024-11-28T16:22:55.430403+00:00 [queued]>
[2024-11-28T16:22:56.632+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-28T16:22:56.647+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-11-28 16:22:55.430403+00:00
[2024-11-28T16:22:56.657+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'stream_data_from_api', 'manual__2024-11-28T16:22:55.430403+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmpk0fhoe73']
[2024-11-28T16:22:56.655+0000] {standard_task_runner.py:72} INFO - Started process 343 to run task
[2024-11-28T16:22:56.661+0000] {standard_task_runner.py:105} INFO - Job 63: Subtask stream_data_from_api
[2024-11-28T16:22:56.711+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.stream_data_from_api manual__2024-11-28T16:22:55.430403+00:00 [running]> on host 3ed14f58f772
[2024-11-28T16:22:56.799+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T16:22:55.430403+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T16:22:55.430403+00:00'
[2024-11-28T16:22:56.804+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-28T16:24:37.671+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2024-11-28T16:24:37.673+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-28T16:24:37.676+0000] {process_utils.py:132} INFO - Sending 15 to group 343. PIDs of all processes in the group: [343]
[2024-11-28T16:24:37.678+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 343
[2024-11-28T16:24:37.962+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-11-28T16:24:37.996+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-28T16:24:38.015+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=343, status='terminated', exitcode=0, started='16:22:56') (343) terminated with exit code 0
