[2025-01-13T16:18:07.683+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T16:18:07.700+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:17:00+00:00 [queued]>
[2025-01-13T16:18:07.708+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:17:00+00:00 [queued]>
[2025-01-13T16:18:07.711+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-13T16:18:07.725+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): append_to_database> on 2025-01-13 16:17:00+00:00
[2025-01-13T16:18:07.735+0000] {standard_task_runner.py:72} INFO - Started process 2827 to run task
[2025-01-13T16:18:07.737+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'append_to_database', 'scheduled__2025-01-13T16:17:00+00:00', '--job-id', '423', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmpuwtu322o']
[2025-01-13T16:18:07.741+0000] {standard_task_runner.py:105} INFO - Job 423: Subtask append_to_database
[2025-01-13T16:18:07.798+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:17:00+00:00 [running]> on host 453ac4defedc
[2025-01-13T16:18:07.887+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='append_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T16:17:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-13T16:17:00+00:00'
[2025-01-13T16:18:07.889+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T16:18:07.947+0000] {logging_mixin.py:190} INFO - Kết nối thành công!
[2025-01-13T16:18:07.950+0000] {logging_mixin.py:190} INFO - <class 'str'>
[2025-01-13T16:18:07.952+0000] {logging_mixin.py:190} INFO - None
[2025-01-13T16:18:07.955+0000] {logging_mixin.py:190} INFO - Có lỗi khi thực hiện append_database: The second parameter to executemany must be a sequence, iterator, or generator.
[2025-01-13T16:18:07.961+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T16:18:07.973+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T16:18:07.974+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_information, task_id=append_to_database, run_id=scheduled__2025-01-13T16:17:00+00:00, execution_date=20250113T161700, start_date=20250113T161807, end_date=20250113T161807
[2025-01-13T16:18:08.035+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T16:18:08.052+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T16:18:08.057+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
